### ISSUE TITLE
Can't login ghcr.io during release

### ISSUE THREAD

**Issue by takaishi** [reproio/send-alb-metrics-to-datadog#36]
I tried to release v0.0.2 by merging https://github.com/reproio/send-alb-metrics-to-datadog/pull/33, but GHA Workflow failed.

The workflow logins to ghcr.io:

```
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: reproiobot
          password: ${{ secrets.CR_PAT }}
```

But maybe token doesn't have permission.

```
Logging into ghcr.io...
Error: Error response from daemon: Get "https://ghcr.io/v2/": denied: denied
```
